import type { PVRecord } from "./types"

export const mockPVRecords: PVRecord[] = [
  {
    id: "pv-001",
    name: "Aaron Vanmarcke",
    description: "Overvallen, GSM gestolen. iPhone 17, er waren camera's aanwezig.",
    location: "Station van Kortrijk",
    municipality: "Kortrijk",
    datetime: "2024-01-15T16:45",
    suspectKnown: false,
    zoneLabel: "VLAS",
    email: "aaron.vanmarcke@gmail.com",
    phone: "0472966184",
    confirmed: false,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "pv-002",
    name: "Marie Dupont",
    description: "Fiets gestolen aan het winkelcentrum. Blauwe Gazelle fiets met mandje.",
    location: "K in Kortrijk",
    municipality: "Kortrijk",
    datetime: "2024-01-14T10:30",
    suspectKnown: false,
    zoneLabel: "VLAS",
    email: "marie.dupont@email.be",
    phone: "0486123456",
    confirmed: true,
    createdAt: new Date("2024-01-14"),
  },
  {
    id: "pv-003",
    name: "Jan Peeters",
    description: "Auto-inbraak, laptop en tas gestolen uit voertuig. Verdachte persoon gezien.",
    location: "Parking Grote Markt",
    municipality: "Brugge",
    datetime: "2024-01-13T22:15",
    suspectKnown: true,
    zoneLabel: "BRUGGE",
    email: "jan.peeters@hotmail.com",
    phone: "0495789012",
    confirmed: true,
    createdAt: new Date("2024-01-13"),
  },
  {
    id: "pv-004",
    name: "Sophie Claes",
    description: "Handtas gestolen in café. Portefeuille met ID en bankkaarten.",
    location: "Café De Kroeg, Markt 15",
    municipality: "Gent",
    datetime: "2024-01-12T21:00",
    suspectKnown: false,
    zoneLabel: "GENT",
    email: "sophie.claes@gmail.com",
    phone: "0478345678",
    confirmed: false,
    createdAt: new Date("2024-01-12"),
  },
]
